### ISSUE TITLE
Cannot read property 'tileType' of undefined

### ISSUE THREAD

**Issue by TechnoX** [TechnoX/rcj-rescue-scoring#10]
[2017-03-21 17:21:41.899] [ERROR] main - TypeError: Cannot read property 'tileType' of undefined
    at Object.module.exports.findPath (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/helper/pathFinder.js:15:29)
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/models/lineMap.js:73:20
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:3702:16
    at next (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:2920:5)
    at next (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:3033:7)
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/query.js:2741:18
    at newTickHandler (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Ziron** [comment]
Caused by missing start tile

**Comment by TechnoX** [comment]
Kan du neka att spara en karta med finished som saknar start-tile? Och skicka nått fint error meddelande? :P

**Comment by TechnoX** [comment]
Fixed in rewrite branch
