### ISSUE TITLE
Error: Map "Testbana 55" is not finished!

### ISSUE THREAD

**Issue by TechnoX** [TechnoX/rcj-rescue-scoring#11]
Can't create run.

[2017-03-21 17:43:54.731] [ERROR] main - Error: Map "Testbana 55" is not finished!
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/models/lineRun.js:63:13
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:3702:16
    at next (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:2920:5)
    at next (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/model.js:3033:7)
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/query.js:2741:18
    at newTickHandler (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Ziron** [comment]
Set "finished" flag from editor. Front-end issue

**Comment by TechnoX** [comment]
Fixat!
