### ISSUE TITLE
Server crasch

### ISSUE THREAD

**Issue by TechnoX** [TechnoX/rcj-rescue-scoring#13]
Servern kraschade, tror inte det översta är relevant, men klistra in det. 

    2017-03-21T21:02:12.864+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:41984 #5 (5 connections now open)
    2017-03-21T21:02:15.482+0100 I COMMAND  [conn1] command rcj-rewrite.linemaps command: find { find: "linemaps", filter: { _id: ObjectId('58d16c56fb0faf1a884aa6b4') }, projection: {}, limit: 1, singleBatch: true, batchSize: 1 } planSummary: IDHACK keysExamined:1 docsExamined:1 idhack:1 cursorExhausted:1 keyUpdates:0 writeConflicts:0 numYields:0 nreturned:1 reslen:3138 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_query 104ms
    events.js:160
          throw er; // Unhandled 'error' event
          ^
    
    TypeError: Cannot read property 'constructor' of undefined
        at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/routes/api/lineRuns.js:207:22
        at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/query.js:2741:18
        at newTickHandler (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mpromise/lib/promise.js:234:18)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    2017-03-21T21:22:28.033+0100 I NETWORK  [conn5] end connection 127.0.0.1:41984 (4 connections now open)
    2017-03-21T21:22:28.033+0100 I NETWORK  [conn4] end connection 127.0.0.1:41982 (3 connections now open)
    2017-03-21T21:22:28.033+0100 I NETWORK  [conn1] end connection 127.0.0.1:41976 (2 connections now open)

**Comment by Ziron** [comment]
Added nullcheck
