### ISSUE TITLE
When posting maze run to line? 

### ISSUE THREAD

**Issue by TechnoX** [TechnoX/rcj-rescue-scoring#19]
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at copyProperties (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/routes/api/lineRuns.js:224:24)
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/routes/api/lineRuns.js:241:15
    at /home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mongoose/lib/query.js:2741:18
    at newTickHandler (/home/fredrik/Documents/Programmering/node/rcj-rescue-scoring/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by TechnoX** [comment]
I don't think this is relevant anymore. If it is someone will open a new issue :)
