### ISSUE TITLE
Broken navigation

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#30]
![linetilesetbug](https://user-images.githubusercontent.com/5030127/28166055-bfb63c44-67d6-11e7-9a2d-016e624b04d5.png)

The section "Line" is not available in the navigation (Home/Admin/Line/Tilesets). It should be "Junior" instead (where Junior is the selected competition name). Throws 404 otherwise.

Not Found
404
Error: Not Found
    at /var/www/html/rcj-rescue-scoring/app.js:141:13
    at Layer.handle [as handle_request] (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:269:13)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:311:12)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at Immediate.next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at Immediate.<anonymous> (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:568:15)
    at runCallback (timers.js:674:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by TechnoX** [comment]
The problem here is that the tileset does not belong to any competition (in your case Junior) so the competition name is not available on this page. 

However a 404 is not correct either. 

Suggestions? :)

**Comment by janblumenkamp** [comment]
The tile set page is a subpage of any competition, but it is always the same page.
I see this options:
1) The redirection depends on the context (if coming from Competition A to the tileset view then you should be able to go back to Competition A in the navigation).
2) Link the tileset page at this page and not under the competitions:
![adminview](https://user-images.githubusercontent.com/5030127/28231777-8f92de74-68ed-11e7-93c8-9025dc7c81b4.png)
This is logical as the tilepages do not depend on any competition.
3) connect the tilesets to a competition, but I don't think that makes sense.
I'd go for option 1 or 2, depending on what is easier to implement.

**Comment by TechnoX** [comment]
2 is easiest. I will fix it.

**Comment by TechnoX** [comment]
Fixed in commit #c01282a230ce5971d23fc7708c34714beea0ea90
