### ISSUE TITLE
Maze map editor not working

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#32]
When clicking on the Maze Maps overview, following message appears in the console:

`[2017-07-13 14:50:20.710] [ERROR] main - { Error: Not Found
    at /var/www/html/rcj-rescue-scoring/app.js:141:13
    at Layer.handle [as handle_request] (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:269:13)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:311:12)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3) status: 404 }
[2017-07-13 14:50:20.856] [ERROR] main - { Error: Not Found
    at /var/www/html/rcj-rescue-scoring/app.js:141:13
    at Layer.handle [as handle_request] (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:269:13)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:311:12)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3) status: 404 }
`
It is possible to open the editor, but in the editor, changing the size does not change the map. Following message is thrown in the JS console in the chrome developer tools:
`angular.js:88 Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.6.5/$injector/unpr?p0=%24%24HashMapProvider%2…eQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue
    at angular.js:88
    at angular.js:4826
    at Object.d [as get] (angular.js:4981)
    at angular.js:4831
    at d (angular.js:4981)
    at e (angular.js:5006)
    at Object.invoke (angular.js:5032)
    at angular.js:4832
    at d (angular.js:4981)
    at e (angular.js:5006)`

Saving the empty map does not actually save it

**Comment by TechnoX** [comment]
Fixed in commit #a76ab96
