### ISSUE TITLE
Error message in NodeJS console after every page load, no matter where

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#38]
`[2017-07-13 23:40:14.410] [ERROR] main - { Error: Not Found
    at /var/www/html/rcj-rescue-scoring/app.js:141:13
    at Layer.handle [as handle_request] (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:269:13)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:311:12)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3) status: 404 }
[2017-07-13 23:40:14.550] [ERROR] main - { Error: Not Found
    at /var/www/html/rcj-rescue-scoring/app.js:141:13
    at Layer.handle [as handle_request] (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:269:13)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:311:12)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3)
    at next (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:188:10)
    at /var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:190:16
    at Function.match_layer (/var/www/html/rcj-rescue-scoring/node_modules/express/lib/router/index.js:294:3) status: 404 }`

**Comment by janblumenkamp** [comment]
This issue persists with the newest commits/version (has nothing to do with #35)

**Comment by TechnoX** [comment]
This is because bootstrap on @rrrobo git account is missing a scss folder. I print the missing URLs in the terminal (server-side) so it can be traced to what is generating the 404. It is a lot of files from a missing scss file in the components/bootstrap folder. 

Maybe @rrrobo can fix it since bower gets the source from you?

**Comment by rrrobo** [comment]
In the latest version at now(c2d7415), bootstrap is supposed to get from bower (v4.0 beta). This problem does not happen now.
