### ISSUE TITLE
Error: Cannot find module 'compression'

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#71]
When starting the server in the console

```
node server.js 
module.js:471
    throw err;
    ^

Error: Cannot find module 'compression'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/rcj-rescue-scoring/app.js:10:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by Ziron** [comment]
Run "npm install" to update backend packages
